name: Build App

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  lint-app:
    runs-on: ubuntu-latest
    name: Build App

    steps:
      - uses: actions/checkout@v3

      - name: 'Use Node 16.20'
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Build'
        run: npm run build
